export const SET_ALL_EXERCISES = "SET_ALL_EXERCISES";
export const SET_BODY_PARTS = "SET_BODY_PARTS";

export const SELECT_BODY_PART = "SELECT_BODY_PART";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const UNSELECT_BODY_PART = "UNSELECT_BODY_PART";

export const SET_EXERCISE_DETAIL = "SET_EXERCISE_DETAIL";

export const SET_THEME = "SET_THEME";
